# Generated by Django 5.2 on 2025-08-18 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('3D', '3D'), ('2D', '2D')], max_length=255)),
                ('furniture_style', models.CharField(choices=[('modern', 'Modern'), ('archaic', 'Archaic')], default=None, max_length=255, null=True)),
                ('resolution', models.CharField(choices=[('HD', 'HD (1080p)'), ('UHD', 'UHD (2160p)')], default=None, max_length=255, null=True)),
                ('show_measurements', models.BooleanField(default=None, null=True)),
                ('show_furniture', models.BooleanField(default=None, null=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customer_first_name', models.CharField(max_length=255)),
                ('customer_last_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('germany', 'Germany'), ('austria', 'Austria'), ('switzerland', 'Switzerland')], max_length=255)),
            ],
        ),
    ]
